<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7zz0B6X\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7zz0B6X/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7zz0B6X.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7zz0B6X\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7zz0B6X\App_KernelDevDebugContainer([
    'container.build_hash' => '7zz0B6X',
    'container.build_id' => 'e523e4b6',
    'container.build_time' => 1611325480,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7zz0B6X');
